### ISSUE TITLE
Improve getting current players

### ISSUE THREAD

**Issue by lukatarman** [lukatarman/steam-game-stats-backend#119]
## Description
As we currently get the "current players" of a game, it's very messy. some games get updated multiple times per day, some don't get updated at all. Implement a way to more consistently get the current players for all games.

## Technical Design
Suggestion: 
-Add property to game class. Something along the lines of "hasBeenCheckedForLatestTimePeriod". Should be boolean. 
-When you do a DB call for getting and adding current players, it should check that this property is false. When current players are added, before changes are persisted to DB, you set this property to true.
-Maybe add aggregator that changes all these values to false on every "x time period"

**Comment by kaleemullah786** [comment]
hey, I would like to work on this

**Comment by lukatarman** [comment]
Closing issue, as this is not a problem actually, we are already doing this with our getXgamesCheckedMoreThanYmsAgo() database call.
