### ISSUE TITLE
Add trending games feature.

### ISSUE THREAD

**Issue by lukatarman** [lukatarman/steam-game-stats-backend#3]
## Description
Introduce a list of **trending games** which is created and maintained by the system. The default list configuration should be: 
- show names of 10 trending games
- show their current players
- show player increase in % looking back 1 month
- order by player increase
- update once daily
In its first iteration the trending games list is not configurable. Later it should be.

## Technical Design
- ...

## Resources
- [frontend issue](https://github.com/lukatarman/steam-game-stats-frontend/issues/15)
- [MongoDB Views](https://www.mongodb.com/docs/manual/core/views/)

**Comment by stas-at-ibm** [comment]
@lukatarman what did you mean by this bulletpoint?

> - **[highest]** Ability to subscribe to games you are interested in only. Prioritizing displaying games you follow.

**Comment by stas-at-ibm** [comment]
I realized that we don't need a data model here. Just MongoDB views and a REST API. Here is the documentation for views: [link](https://www.mongodb.com/docs/manual/core/views/). This makes the technical design easier.

**Comment by lukatarman** [comment]
See issue: #2 for more info

**Comment by lukatarman** [comment]
Calculate in code at the endpoint for now.
