### ISSUE TITLE
Store additional details of a game.

### ISSUE THREAD

**Issue by lukatarman** [lukatarman/steam-game-stats-backend#5]
## Description
Decide which additional details of a game should be stored: release date, price, description, single-/multiplayer, awards, tags or something else.
Implement some additional methods for game player statistics: gain, peak, average, median, standard deviation of players in time range.

## Technical Design
- decide on additional properties
- extend game data model
- implement statistic methods which make sense
- decide where to get the data
- decide where to put the logic for gathering additional data
  - it can be done when a game is identified
  - it can be done with a separate aggregator

## Resources
- [median](https://www.educba.com/median-formula/)
- [standard deviation](https://www.vedantu.com/formula/standard-deviation-formulas)

**Comment by stas-at-ibm** [comment]
> There is a problem with filtering whether or not an entry in the Steam API is a game or not. Filtering through game names is unreliable, as the wording is inconsistent.
> 
> Also, steamcharts sometimes returns an error for actual games. However, their "30-day average" player number still shows a number. A solution to this could be to check if steamcharts returns and error AND the 30-day average player number is 0.
> 
> Another option is to somehow parse the mini images we will add to the class. They have something on them if they're not games.

Irrelevant for the feature described above. If this is still relevant please open a bug issue.

**Comment by lukatarman** [comment]
Add year of release, developer.

**Comment by lukatarman** [comment]
Add game genres!

**Comment by lukatarman** [comment]
Think about adding whether or not game is free to play

**Comment by lukatarman** [comment]
> Think about adding whether or not game is free to play

No need, free to play is included in genres list.
