### ISSUE TITLE
Add database integration test setup.

### ISSUE THREAD

**Issue by stas-at-ibm** [lukatarman/steam-game-stats-backend#55]
## Description
Add integration tests setup for database layer (mongedb). All the db operations are untested but make up a large part of the current logic. Preferably use package in first link.

## Technical Design
- install package
- configure package
- add test setup and boilerplate
- add one example test

## Resources
- [in memory db](https://javascript.plainenglish.io/how-to-test-with-mongodb-with-node-js-b05f94aa17a)
- check out this post: https://threedots.tech/post/database-integration-testing/
- and this: https://www.thecodebuzz.com/integration-testing-best-practices-agile/

**Comment by lukatarman** [comment]
Look up mongodb nodejs integration tests
